<h1>Лабораторная работа №2</h1>
<h1>Работа с библиотеками NumPy, Pandas</h1>
<h2>Практика по лекции. (Домашнее задание находится ниже)</h2>

<h3>Подключение библиотеки NumPy</h3>

In [1]:
import numpy as np

<h3>Работа с библиотекой NumPy</h3>

In [2]:
a = np.array([11,12,13,14])
a

array([11, 12, 13, 14])

In [3]:
b = np.array([[11.1, 22.2],[33.3,44.4]])
b

array([[11.1, 22.2],
       [33.3, 44.4]])

In [4]:
c = np.array([[11,22,33],[44,55,66]])
c

array([[11, 22, 33],
       [44, 55, 66]])

In [5]:
d = np.array(((10,20,30),(40,50,60)))
d

array([[10, 20, 30],
       [40, 50, 60]])

In [6]:
e = np.array([(10,20,30),(40,50,60),(70,80,90)])
e

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
f = np.array(((11,22,33),(44,55,66)),dtype=float)
f

array([[11., 22., 33.],
       [44., 55., 66.]])

In [8]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
np.arange(5,9)

array([5, 6, 7, 8])

In [12]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [13]:
np.arange(1,12,2.5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [14]:
np.arange(0,24).reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
np.linspace(10,100,7)

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [16]:
np.random.random(5)


array([0.35971492, 0.59290021, 0.89054921, 0.16816924, 0.84593692])

In [17]:
np.random.random((5,4))


array([[0.4351119 , 0.54577162, 0.84756688, 0.79175604],
       [0.19400211, 0.17929242, 0.45554571, 0.63493142],
       [0.31703673, 0.59478412, 0.83429421, 0.93899916],
       [0.1816947 , 0.95822988, 0.75529481, 0.06646754],
       [0.23336037, 0.37834422, 0.50184595, 0.2215742 ]])

In [18]:
nn = np.array(((2,2,2),(3,3,3),(4,4,4)), dtype=float)

In [19]:
nn[::2]

array([[2., 2., 2.],
       [4., 4., 4.]])

In [20]:
nn[:1:2]

array([[2., 2., 2.]])

In [21]:
nn[0,2]=10
nn

array([[ 2.,  2., 10.],
       [ 3.,  3.,  3.],
       [ 4.,  4.,  4.]])

In [22]:
for i in nn:
    print(i**2)

[  4.   4. 100.]
[9. 9. 9.]
[16. 16. 16.]


<p> Примеры пакета NumPy.</p>

In [23]:
l1 = [100,101,102,103]
arr1 = np.array(l1)
print(arr1)
print(arr1.dtype)
type(arr1)

[100 101 102 103]
int32


numpy.ndarray

<p>Проверка размерности массива</p>

In [24]:
b = np.array([(100,200,100),(200,100,200)])
b.shape

(2, 3)

<p>Создание массива типа float</p>

In [25]:
b

array([[100, 200, 100],
       [200, 100, 200]])

<p>Арифметические действия с массивами</p>

In [26]:
for n in range(len(l1)):
    l1[n] += 1
arr1 += 1
print(l1)
print(arr1)

[101, 102, 103, 104]
[101 102 103 104]


In [27]:
for n in range(len(l1)):
    l1[n] -= 1
arr1 -= 1
print(l1)
print(arr1)

[100, 101, 102, 103]
[100 101 102 103]


<p>Дополнительные возможности получения массивов с помощью функций zeros(),ones(),arrange(), linspace()</p>

In [28]:
zeros = np.zeros(5)
ones = np.ones(5)
aran = np.arange(5)
lins = np.linspace(5,6,10)

print(zeros)
print(ones)
print(aran)
print(lins)
print(ones+aran)
print(ones*aran)


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]
[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]
[1. 2. 3. 4. 5.]
[0. 1. 2. 3. 4.]


<p>Индексация и двумерные массивы</p>

In [29]:
aran = np.arange(20).reshape(2,10)
print("First = ", aran)
print("Second = ", aran[:,2:])

First =  [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
Second =  [[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


<p> Применение метода np.newaxis</p>

In [30]:
aa = np.arange(10)
print(aa.shape)

aa2 = aa[np.newaxis,:]
aa2.shape

(10,)


(1, 10)

<h3>Подключение библиотеки Pandas</h3>

In [31]:
import pandas as pd

<p>Создание DataFrame с разными типами данных</p>

In [32]:
df = pd.DataFrame({'car': ['Tesla', 'BMW', 'KIA'], 'number': [333,222,111]})
df

car  number
0  Tesla     333
1    BMW     222
2    KIA     111

<p>Импорт данных из .csv</p>

In [33]:
df_data = pd.read_csv('train.csv')
df_data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [34]:
df_data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [35]:
df_data.value_counts()

PassengerId  Survived  Pclass  Name                                                  Sex     Age   SibSp  Parch  Ticket    Fare      Cabin  Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)   female  38.0  1      0      PC 17599  71.2833   C85    C           1
572          1         1       Appleton, Mrs. Edward Dale (Charlotte Lamson)         female  53.0  2      0      11769     51.4792   C101   S           1
578          1         1       Silvey, Mrs. William Baird (Alice Munger)             female  39.0  1      0      13507     55.9000   E44    S           1
582          1         1       Thayer, Mrs. John Borland (Marian Longstreth Morris)  female  39.0  1      1      17421     110.8833  C68    C           1
584          0         1       Ross, Mr. John Hugo                                   male    36.0  0      0      13049     40.1250   A10    C           1
                                                                                 

In [36]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [37]:
dat = df_data.sort_values(by='Age', ascending=False)
aa = dat.head(10)
aa

PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   
493          494         0       1               Artagaveytia, Mr. Ramon   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
672          673         0       2           Mitchell, Mr. Henry Michael   
745          746         0       1          Crosby, Capt. Edward Gifford   
33            34         0       2                 Wheadon, Mr. Edward H   
54            55         0       1        Ostby, Mr. Engelhart Cornelius   
280          281         0       3                      Duane, Mr. Frank   

      Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
630  male  80.0      0      0       27042  30.0000   A23        S  
851  male  74.0      0      0      347060   7.7750   NaN        S  
493  male  71.0      0      0    PC 17609  49.5042   NaN        C  
96   male  71.0      0      0    PC 17754  34.6542    A5        C  
116  male  70.5      0      0      370369   7.7500   NaN        Q  
672  male  70.0      0      0  C.A. 24580  10.5000   NaN        S  
745  male  70.0      1      1   WE/P 5735  71.0000   B22        S  
33   male  66.0      0      0  C.A. 24579  10.5000   NaN        S  
54   male  65.0      0      1      113509  61.9792   B30        C  
280  male  65.0      0      0      336439   7.7500   NaN        Q

In [38]:
df_data['Age'].sum()

21205.17

In [39]:
df_data.groupby(['Pclass']).sum()

PassengerId  Survived  \
Pclass                          
1             99705       136   
2             82056        87   
3            215625       119   

                                                     Name  \
Pclass                                                      
1       Cumings, Mrs. John Bradley (Florence Briggs Th...   
2       Nasser, Mrs. Nicholas (Adele Achem)Hewlett, Mr...   
3       Braund, Mr. Owen HarrisHeikkinen, Miss. LainaA...   

                                                      Sex      Age  SibSp  \
Pclass                                                                      
1       femalefemalemalefemalemalemalemalefemalemalema...  7111.42     90   
2       femalefemalemalemalemalemalefemalefemalefemale...  5168.83     74   
3       malefemalemalemalemalefemalefemalemalemalefema...  8924.92    302   

        Parch                                             Ticket        Fare  \
Pclass                                                                         
1          77  PC 175991138031746311378311378819950PC 17601PC...  18177.4125   
2          70  237736248706244373239865248698C.A. 2457911668S...   3801.8417   
3         193  A/5 21171STON/O2. 3101282373450330877349909347...   6714.6951   

                                                    Cabin  \
Pclass                                                      
1       C85C123E46C103A6C23 C25 C27B78D33B30C52B28C83C...   
2                D56F33E101F2F4F2DE101DF2F33DF33F4E101E77   
3              G6F G73F E69G6G6G6E10F G63F G73E121F38E121   

                                                 Embarked  
Pclass                                                     
1       CSSSSSCCCSCCSSCSSSCCSSCSSSCSCSSSCCSSCCCCCSSQSS...  
2       CSSSSSSCSSSSSSSSSSSSCSSSCSSSSSSSCSSSSSSSSSSSSS...  
3       SSSQSSSSSSQSCQSSCQSQCSSCSCQSQQCSSSCSCSCSSSSCSS...

<p>Отбор данных по условию</p>

In [40]:
print(df_data[df_data['Sex'] == 'female'])
print('*********************')
print(df_data[(df_data['Sex'] == 'female') & (df_data['Age'] == 35.0)])

     PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ... 

<h1> HOMEWORK LAB 2</h1>

<p>Создайте одномерный массив my_array, в котором по порядку все числа до 100,
кратные 5</p>

In [41]:
my_array = np.arange(5,101,5).reshape(4,5)
my_array

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

<p>Из полученного массива получить массив с кратными 10 числами</p>

In [42]:
(my_array[my_array%10==0]).reshape(2,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

Получить двумерный массив с двумя столбцами

In [43]:
a = np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

Получите набор my_second_array, в котором все элементы меньше предыдущего
исходного на 5

In [44]:
my_second_array = my_array - 5
my_second_array

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для
транспонирования матрицы.

In [45]:
r = np.hstack((a.T, my_second_array.reshape(2,10)))
r

array([[ 1.,  1.,  0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 1.,  1., 50., 55., 60., 65., 70., 75., 80., 85., 90., 95.]])

Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для
транспонирования матрицы

In [46]:
a = my_array[1:3]
a

array([[30, 35, 40, 45, 50],
       [55, 60, 65, 70, 75]])

In [47]:
b = a/my_array[:1]
b

array([[ 6.        ,  3.5       ,  2.66666667,  2.25      ,  2.        ],
       [11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ]])

Оставить только те значения, которые не изменились после деления

In [48]:
unCh = a[a == b]
unCh


array([], dtype=int32)

Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [49]:
a = my_array[:3]
a

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50],
       [55, 60, 65, 70, 75]])

In [50]:
a[0] = a[1]
a

array([[30, 35, 40, 45, 50],
       [30, 35, 40, 45, 50],
       [55, 60, 65, 70, 75]])

Получить среднее, медиану и стандартное отклонение для каждой строки,
используя команды np.mean(), np.median(), np.std()

In [51]:
np.mean(my_array)

58.75

In [52]:
np.median(my_array)

52.5

In [53]:
np.std(my_array)

21.901769334919038

Сделать нормализацию на максимальное значение вдоль строк, поделив
каждый элемент массива на max() вдоль строк

In [54]:
(my_array[0]).max()


50

In [55]:
(my_array[1]).max()


50

In [56]:
(my_array[2]).max()

75

<h2>Использование команд библиотеки pandas</h2>
<p>Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание
данных смотрите ниже.</p>

In [57]:
global_data = pd.read_csv('global.csv')
global_data

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

Считайте несколько первых записей таблицы (head())

In [58]:
global_data.head(10)

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   
5      Albania  2017                -                -                -   
6      Albania  2018        2,866,376        1,728,969        1,137,407   
7      Albania  2019        2,854,191        1,747,593        1,106,598   
8      Albania  2020        2,837,849        1,762,645        1,075,204   
9      Albania  2021        2,811,666        1,770,478        1,041,188   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   
5                105            79.0      10.870       8.150          1.491   
6                105            79.0      10.517       8.308           1.44   
7                104            79.0      10.343       8.480          1.414   
8                104            77.0      10.285      10.785            1.4   
9                  -            76.0      10.240      11.325           1.39   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0  
5                   8.3           -  
6                   8.3         0.0  
7                   8.4         0.0  
8                   8.4        -1.0  
9                   8.4        -1.0

Определите размерность данного фрейма (shape())

In [59]:
global_data.shape

(1073, 12)

Выведите название заголовков столбцов фрейма (columns)

In [60]:
global_data.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

Получите описание всех переменных (полей) (info())

In [61]:
global_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


Удалите строки, не содержащие значения в столбце «Total Population» - “-”

In [62]:
global_data1 = global_data[global_data["Total Population"] != "-"]
global_data1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

Получите описательную статистику по переменным (например, max(), min(),
describe())

In [63]:
global_data1.describe()

Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000

Выполните сортировку данных по нескольким критериям

In [64]:
global_data1.sort_values(by='Year', ascending=False)

Country  Year Total Population Urban Population  \
1072          Zimbabwe  2021       15,993,524        5,166,388   
225            Croatia  2021        3,879,000        2,245,088   
922           Suriname  2021          612,985          405,913   
230               Cuba  2021       11,256,372        8,700,275   
600   Marshall Islands  2021           42,050           32,867   
...                ...   ...              ...              ...   
567         Madagascar  2018       26,846,541        9,984,497   
562              Macao  2018          650,991          650,991   
557         Luxembourg  2018          607,950          553,119   
552          Lithuania  2018        2,801,543        1,896,056   
537            Liberia  2018        4,889,391        2,500,972   

     Rural Population Population Density Life Expectancy  Birth Rate  \
1072       10,827,136                  -            59.0      30.537   
225         1,633,912                  -            76.0       9.400   
922           207,072                  -            70.0      18.154   
230         2,556,097                  -            74.0       8.922   
600             9,183                  -            65.0      19.280   
...               ...                ...             ...         ...   
567        16,862,044                 46            65.0      32.088   
562                 -             19,787            85.0      10.621   
557            54,831                236            82.0      10.300   
552           905,487                 45            76.0      10.000   
537         2,388,419                 51            61.0      32.706   

      Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
1072       9.057          3.491                  35.7         2.0  
225       16.200           1.62                   3.9        -4.0  
922        8.667          2.348                  15.4         1.0  
230       14.652          1.442                   4.0         0.0  
600        7.556          2.729                  24.8        -3.0  
...          ...            ...                   ...         ...  
567        6.736          4.043                  45.2         3.0  
562        3.860          1.104                     -         2.0  
557        7.100           1.38                   2.3         2.0  
552       14.100           1.63                   3.3        -1.0  
537        8.793          4.336                  60.9         2.0  

[864 rows x 12 columns]

In [65]:
global_data1.sort_values(by='Country', ascending=False)

Country  Year Total Population Urban Population Rural Population  \
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
...           ...   ...              ...              ...              ...   
9         Albania  2021        2,811,666        1,770,478        1,041,188   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1072                  -            59.0      30.537       9.057   
1071                 41            61.0      31.009       8.132   
1070                 40            61.0      31.518       8.043   
1069                 39            61.0      32.074       7.972   
1067                  -            61.0      34.511       6.973   
...                 ...             ...         ...         ...   
9                     -            76.0      10.240      11.325   
3                    60            63.0      36.051       7.113   
2                    58            64.0      36.466       6.791   
4                     -            62.0      35.842       7.344   
1                    56            63.0      36.927       6.981   

     Fertility Rate Infant Mortality Rate Growth Rate  
1072          3.491                  35.7         2.0  
1071          3.545                  36.6         2.0  
1070          3.599                  37.1         2.0  
1069          3.659                  38.0         2.0  
1067          4.308                  40.2         3.0  
...             ...                   ...         ...  
9              1.39                   8.4        -1.0  
3              4.75                  44.8         3.0  
2              4.87                  46.3         3.0  
4             4.643                  43.4         3.0  
1             5.002                  47.8         3.0  

[864 rows x 12 columns]

Выведите название страны, которая имеет максимальную численность населения

In [66]:
max_population_county = global_data1[global_data1['Total Population'] == global_data1['Total Population'].max()]['Country']
max_population_county

832    Seychelles
Name: Country, dtype: object

Выведите название страны, которая имеет минимальную численность населения

In [67]:
min_population_county = global_data1[global_data1['Total Population'] == global_data1['Total Population'].min()]['Country']
min_population_county

257    Djibouti
Name: Country, dtype: object

Экспорт фрейма в MS Excel

In [68]:
global_data1.to_excel(r'C:\Users\Aiana Sagynbek\PycharmProjects\bigDataLabs\labWork2\myData.xlsx')